displayName: Sales Specialist – Microsoft Cloud
schemaName: crd3a_agent
accessControlPolicy: GroupMembership
authenticationMode: Integrated
authenticationTrigger: Always
configuration:
  channels:
    - channelId: MsTeams

    - channelId: Microsoft365Copilot

  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  publishOnImport: true
  gPTSettings:
    defaultSchemaName: crd3a_agent.gpt.default

  isLightweightBot: false
  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    optInUseLatestModels: true

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-03-26T21:47:24.0000000Z
template: default-2.1.0
language: 1034